project:
  title: "Ressources et supports du Dispositif d’Écologie Numérique (DEN)"
  output-dir: ./_site/

website:
  page-navigation: true
  back-to-top-navigation: true
  page-footer: "Copyright UMR MARBEC (IRD, Ifremer, Montpellier university, CNRS)"
  search:
    location: navbar
    type: textbox
    copy-button: true
    show-item-context: tree
  navbar:
    left:
      - text: "Liens utiles"
        href: pages/liens.qmd
      - text: "Aide"
        menu:
          - text: "Poser une question"
            href: https://github.com/umr-marbec/den_pages/discussions
    right:
      - text: "En"
        href: en
    tools:
      - icon: github
        text: "Code source"
        href: https://github.com/umr-marbec/den_pages
      - icon: box-arrow-up-right
        text: "Site global du DEN"
        href: https://umr-marbec.fr/recherche/dispositifs-de-recherche/den/
  sidebar:
    style: "docked"
    contents:
      - text: "Serveurs"
        href: pages/serveurs/index_serveurs.qmd
        contents:
          - section: "Marbec DATA"
            href: pages/serveurs/marbec_data/index_marbec_data.qmd
            contents:
              - text: "Gestion des Fichiers"
                href: pages/serveurs/marbec_data/manage_files.qmd
          - section: "Marbec GPU"
            href: pages/serveurs/marbec_gpu/index_marbec_gpu.qmd
            contents:
              - text: "Initiation"
                href: pages/serveurs/marbec_gpu/intro_marbec_gpu.qmd
              - text: "Guide des Commandes Utiles"
                href: pages/serveurs/marbec_gpu/basic_command.qmd
              - text: "Accéder aux dossiers de MARBEC-DATA"
                href: pages/serveurs/marbec_gpu/marbec-data_folders.qmd
              - text: "Soumission SLURM  : Exemple R/Python Basique"
                href: pages/serveurs/marbec_gpu/basic_example.qmd
              - text: "R Scripts Running"
                href: pages/serveurs/marbec_gpu/run_r_script.qmd
      - text: "Formations"
        href: pages/formations/index_formations.qmd
        contents:
          - text: "Formation Git"
            href : pages/formations/git.qmd
          - text: "Formation Tidyverse"
            href : pages/formations/tidyverse.qmd
      - section: "Système de contrôle de version"
        href: pages/git/index_git.qmd
        contents:
          - text: "Miroir depuis Github vers un dépôt git"
            href: pages/git/miroir_github_git.qmd
      - section: "Packages et logiciels"
        href: pages/packages_logiciels/index_packages_logiciels.qmd
        contents:
          - text: "Package R sparck"
            href: pages/packages_logiciels/r_package_sparck.qmd
          - text: "Logiciel Ichthyop"
            href: pages/packages_logiciels/ichthyop.qmd
          - text: "Modèle Osmose"
            href: pages/packages_logiciels/osmose.qmd
      - text: "Calendrier"
        href: pages/calendrier/calendrier.qmd
      - text: "Support global"
        href: pages/support/index_support.qmd
      - text: "Je veux contribuer !"
        href: pages/contribution.qmd

lan: fr
