project:
  title: "Digital Ecology Scheme (DEN) Resources and Materials"
  output-dir: ./_site/en

website:
  page-navigation: true
  back-to-top-navigation: true
  page-footer: "Copyright UMR MARBEC (IRD, Ifremer, Montpellier University, CNRS)"
  search:
    location: navbar
    type: textbox
    copy-button: true
    show-item-context: tree
  navbar:
    left:
      - text: "Useful links"
        href: pages/liens.qmd
      - text: "Help"
        menu:
          - text: "Ask a Question"
            href: https://github.com/umr-marbec/den_pages/discussions
    right:
      - text: "Fr"
        href: ../
    tools:
      - icon: github
        text: "Source code"
        href: https://github.com/umr-marbec/den_pages
      - icon: box-arrow-up-right
        text: "DEN Global Website"
        href: https://umr-marbec.fr/recherche/dispositifs-de-recherche/den/
  sidebar:
    style: "docked"
    contents:
      - text: "Servers"
        href: pages/serveurs/index_serveurs.qmd
        contents:
          - section: "Marbec DATA"
            href: pages/serveurs/marbec_data/index_marbec_data.qmd
            contents:
              - text: "Manage Files"
                href: pages/serveurs/marbec_data/manage_files.qmd
          - section: "Marbec GPU"
            href: pages/serveurs/marbec_gpu/index_marbec_gpu.qmd
            contents:
              - text: "Initiation"
                href: pages/serveurs/marbec_gpu/intro_marbec_gpu.qmd
              - text: "Useful Commands Guide"
                href: pages/serveurs/marbec_gpu/basic_command.qmd
              - text: "Accessing MARBEC-DATA Folders"
                href: pages/serveurs/marbec_gpu/marbec-data_folders.qmd
              - text: "SLURM Submission : Basic R/Python example"
                href: pages/serveurs/marbec_gpu/basic_example.qmd
              - text: "R Scripts Running"
                href: pages/serveurs/marbec_gpu/run_r_script.qmd
      - text: "Training"
        href: pages/formations/index_formations.qmd
        contents:
          - text: "Git training"
            href : pages/formations/git.qmd
          - text: "Tidyverse training "
            href : pages/formations/tidyverse.qmd
      - section: "Version Control System"
        href: pages/git/index_git.qmd
        contents:
          - text: "Mirroring from Github to a Git Repository"
            href: pages/git/miroir_github_git.qmd
      - section: "Packages and software"
        href: pages/packages_logiciels/index_packages_logiciels.qmd
        contents:
          - text: "R package sparck"
            href: pages/packages_logiciels/r_package_sparck.qmd
          - text: "Ichthyop software"
            href: pages/packages_logiciels/ichthyop.qmd
          - text: "Osmose model"
            href: pages/packages_logiciels/osmose.qmd
      - text: "Schedule"
        href: pages/calendrier.qmd
      - text: "Global support"
        href: pages/support/index_support.qmd
      - text: "I want to contribute!"
        href: pages/contribution.qmd

lang: en-US

      
