project:
  type: website

website:
  favicon: ressources/favicon.png  

execute:
  freeze: auto
  default-kernel: knitr

format:
  html:
    theme: pulse
    css: styles.css
    toc: true

profile:
  default: french
  group: [french, english]
