---
format:
  html:
    css: styles.css
---

::: {.content-visible when-profile="french"}
# Bienvenue !

L'objectif de ce site est de centraliser et mettre facilement à disposition des ressources informatiques, procédures et autres supports permettant d'appuyer de manière globale les travaux des personnelles et personnes associées de l'[UMR MARBEC](https://umr-marbec.fr/nous-connaitre/presentation-de-lumr/){.external target="_blank"}. Cette structuration s'appuie notamment sur Dispositif d’Ecologie Numérique, ou [DEN](https://umr-marbec.fr/recherche/dispositifs-de-recherche/den/){.external target="_blank"}, qui est une structure transversale associée à l'UMR. Ces missions sont la mise en place, la coordination et la mutualisation des moyens techniques ainsi que l’échange de méthodologies et de nouvelles approches en support aux aspects numériques des travaux de recherche scientifique.

Vous disposez aussi d'une section [Issues](https://github.com/umr-marbec/den_pages/issues){.external target="_blank"} vous permettant par exemple de faire remonter un problème dans le code source du site ou encore proposer une amélioration ou du contenu. Ces "GitHub Issues" sont vraiment à voir comme des objets s'apparentent davantage à des éléments « à faire » et sont axées sur les tâches à accomplir (par exemple via la création de branche dédié au sujet).

De plus, vous trouverez un [forum de discussion](https://github.com/umr-marbec/den_pages/discussions){.external target="_blank"} afin d'échanger sur des sujets ou des problématiques communes.  Les discussions sont destinées aux conversations qui doivent être transparentes et accessibles, mais qui n'ont pas besoin d'être suivies sur un projet et qui ne sont pas liées au code, contrairement aux "GitHub Issues".

Pour information, l'UMR dispose aussi d'un serveur [Rocket chat](https://www.rocket.chat/){.external target="_blank"} accessible via l'URL suivante https://tchat.ird.fr/home. Il est possible d'accéder à l'espace de travail directement depuis l'URL ou en installant un [client lourd](https://www.rocket.chat/download-apps){.external target="_blank"} (=logiciel) sur votre ordinateur et en ajoutant l'URL dans la section "add workspace". 

Par ailleurs, afin de faciliter l'accès et l'utilisation par le plus grand nombre, vous trouverez ce site et les ressources associées en français (par défaut) mais aussi en anglais (utilisez le bouton à gauche de barre de recherche pour changer de langue).

N'hésitez pas visiter aussi la section ["Je veux contribuer !"](pages/contribution.qmd) si vous disposez de ressources susceptibles d'alimenter celles disponibles via ce site ou même de manière générale si vous voulez contribuer à la mise a disposition de ressources communes.

En cas de besoin spécifique, vous pouvez contacter les représentant(e)s et référent(e)s du DEN à l'adresse suivante : [marbec-den-admin@listes.ird.fr](mailto:marbec-den-admin@listes.ird.fr)

Pour information, ce site a été généré via le système de publication [Quarto](https://quarto.org/){.external target="_blank"}.
:::

::: {.content-visible when-profile="english"}
# Welcome!

The aim of this site is to centralize and provide easy access to informatics resources, procedures and other support for the work of personnel and associates of the [UMR MARBEC](https://umr-marbec.fr/nous-connaitre/presentation-de-lumr/){.external target=“_blank”}. This structuring is based in particular on the Dispositif d'Ecologie Numérique, or [DEN](https://umr-marbec.fr/recherche/dispositifs-de-recherche/den/){.external target=“_blank”}, which is a transversal entity associated with the UMR. Its missions are to set up, coordinate and share technical resources, and to exchange methodologies and new approaches in support of the digital aspects of scientific research.

There's also an [Issues](https://github.com/umr-marbec/den_pages/issues){.external target=“_blank”} section where you can, for example, report a problem in the site's source code, or suggest an improvement or new content. These “GitHub Issues” are really to be seen as objects closely linked to a “to-do list” items, and are focused on tasks to be accomplished (for example, throught the creation of a branch dedicated to the subject).

In addition, you'll find a [discussion forum](https://github.com/umr-marbec/den_pages/discussions){.external target=“_blank”} to exchange ideas on common topics or issues.  Discussions are intended for conversations that need to be transparent and accessible, but do not need to be followed up on a project and are not code-related, unlike “GitHub Issues”.

For your information, UMR also has a [Rocket chat](https://www.rocket.chat/){.external target=“_blank”} server accessible through the following URL https://tchat.ird.fr/home. It is possible to access the workspace directly from the URL or by installing a [heavy client](https://www.rocket.chat/download-apps){.external target=“_blank”} (=software) on your computer and adding the URL in the “add workspace” section. 

Furthermore, to facilitate access and use by many as possible, you'll find this website and related resources in French (by default) but also in English (use the button on the left of the search bar to switch language).

Feel free to visit the [“I want to contribute!”](pages/contribution.qmd) section if you have resources to contribute to those available, or even more generally if you want to contribute to the provision of common resources.

If you have any specific requirements, please contact the DEN representatives at [marbec-den-admin@listes.ird.fr](mailto:marbec-den-admin@listes.ird.fr).

For your information, this site was generated using the [Quarto](https://quarto.org/){.external target=“_blank”} publishing system.
:::