---
format:
  html:
    css: ../../styles.css
---
::: {.content-visible when-profile="french"}
# Calendrier

<div class="calendar-container">
  <iframe width="400" height="215" src="https://drive.ird.fr/apps/calendar/embed/ZBpNdNbz6KS85H95"></iframe>
</div>

<style>
 
  .calendar-container {
    position: relative; 
    width: 130vh;
    height: 100vh; 
    overflow: hidden; 
    background-color: #f1e7ff; 
    border-radius: 10px; 
    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1); 
  }

  iframe {
    position: absolute;
    top: 0; 
    left: 0; 
    width: 80%; 
    height: 80%;
    border: none; 
    border-radius: 10px; 
  }

 
  h1 {
    font-family: 'Arial', sans-serif;
    font-size: 2.5em;
    color: #5e3c85; 
    text-align: center;
    margin-bottom: 20px;
  }

  
  body {
    font-family: 'Arial', sans-serif;
    background-color: #f9f0ff; 
    color: #5e3c85; 
    margin: 0;
    padding: 0;
  }
</style>



:::

::: {.content-visible when-profile="english"}
# Schedule

<div class="calendar-container">
  <iframe width="400" height="215" src="https://drive.ird.fr/apps/calendar/embed/ZBpNdNbz6KS85H95"></iframe>
</div>

<style>
 
  .calendar-container {
    position: relative; 
    width: 130vh;
    height: 100vh; 
    overflow: hidden; 
    background-color: #f1e7ff; 
    border-radius: 10px; 
    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1); 
  }

  iframe {
    position: absolute;
    top: 0; 
    left: 0; 
    width: 80%; 
    height: 80%;
    border: none; 
    border-radius: 10px; 
  }

 
  h1 {
    font-family: 'Arial', sans-serif;
    font-size: 2.5em;
    color: #5e3c85; 
    text-align: center;
    margin-bottom: 20px;
  }

  
  body {
    font-family: 'Arial', sans-serif;
    background-color: #f9f0ff; 
    color: #5e3c85; 
    margin: 0;
    padding: 0;
  }
</style>

:::
