---
format:
  html:
    css: ../styles.css
---

::: {.content-visible when-profile="french"}
Vous faites partir de l'UMR, ou non, et vous avez des bouts de codes, documentations techniques ou n'importe quelles ressources informatiques que vous aimeriez tester, standardiser ou même mutualiser ? Vous avez une idée et vous demandez si le processus associé n'a pas déjà été développé par quelqu'un ? Vous êtes au bon endroit !

Ce site, et par addition les ressources associées, sont le fruit de nombreuses heures de travail et de réflexions communes sur des sujets qui au final sont souvent transervaux entre les personnes. Son but est vraiment de centraliser et standardiser au maximum ce qui a été fait et son succès ne dépend que de la synergie que nous mettons en œuvre pour créer du contenu. Par ailleurs, ces ressources ne sont que la partie émergée de l'iceberg qui favorise les relations et les liens que nous pouvons créer entre nous sur nos travaux.

Si vous voulez contribuer d'une manière ou d'une autre, la clé est vraiment de ne pas se décourager par la tache globale qui peut faire peur, mais vraiment de commencer par un premier pas. Vous constaterez rapidement que derrière un problème ou un obstacle, vous trouverez ici une communauté riche et bienveillante qui saura vous aider, toujours avec un objectif de mutualisation et d'optimisation des ressources informatiques.

Derrière la multitude de types de contenu que nous pouvons partagé entre nous, qui va d'une documentation en markdown jusqu'a des packages ou des logiciels développés par la communauté, l'idée est d'établir entre nous certains standards permettant de garantir l'intégrité et l'interopérabilité des contenus et ressources disponibles. Ces standards peuvent être vus comme des règles, mais en aucun cas ils ne doivent être assimilés à des freins à votre implication. Par exemple si certains points sont bloquants (par exemple la traduction d'une procédure dans une autre langue ou la méconnaissance de l'utilisation des forges telles que les git), tournés vers la communauté et vous trouverez tout l'aide dont vous avez besoin.

De manière générale voici quelques lignes directrices à prendre en compte avant de publier des ressources :

* les ressources de ce site sont dédiées à être utilisé par tous le personnel de l'UMR, mais potentiellement les partenaires associés. Par défaut le contenu doit être publié en français, mais aussi en anglais afin de garantir l'accessibilité au "maximum". Certains contenus, comme les formations, peuvent s'abroger de règles si cela est pertinent. Encore une fois ne vous laissez pas bloqué par la barrière de la langue, vous trouverez forcément quelqu'un de notre communauté qui peut vous aider pour traduire.
* suivante le type de contenu que vous voulez publiez, le mieux est parfois de ce tourner vers des personnes-ressources ou référentes qui pourront vous apporter des solutions ou des propositions pour vous guider dans la mutualisation de vos ressources. La liste de ces personnes clés sera mise à disposition sous peu et en attendant si vous ne savez pas vers qui vous tourner vous pouvez envoyer un mail aux [administrateurs du DEN](mailto:marbec-den-admin@listes.ird.fr).
* toujours dans un but de mutualisation et globalement d'harmonie des templates seront proposés pour les différents types de ressources. En attendant, n'hésitez pas à échanger avec les personnes de la communauté pour essayer de trouver, autant que possible, une structure commune.
* même si l'utilisation des ressources informatique au sein de l'UMR doit vraiment être vu de manière transversale et sans "frontières" associées, la mutualisation et l'accessibilité de ces derniers est vraiment en lien avec le Dispositif d’Ecologie Numérique, ou [DEN](https://umr-marbec.fr/recherche/dispositifs-de-recherche/den/){.external target="_blank"}. Cette entité, transversale au niveau de l'UMR à comme objectifs la mise en place, la coordination et la mutualisation des moyens techniques ainsi que l’échange de méthodologies et de nouvelles approches en support aux aspects numériques des travaux de recherche scientifique. Vous rapprocher de ce dispositif et des sous-entités qui le composent peut être judicieux et vous apporter un support non négligeable au sein de vos activités.
* de par sa nature, ce site est voué à évoluer en lien avec les besoins. N'hésitez pas à faire des suggestions d'améliorations, proposer de nouvelles sections ou même une organisation différente. Au final cela ne pourra être que bénéfique à la communauté.  
:::

::: {.content-visible when-profile="english"}
Do you belong to the UMR, or not, and have some pieces of code, technical documentation or any other informatics resources that you'd like to test, standardize or even share? Do you have an idea and wonder whether the process has already been developed by someone else? Then you've come to the right place!

This site, and by extension the associated resources, are the result of several hours' work and joint reflection on subjects which, in the final analysis, are often transverse between people. Its aim is to centralize and standardize as much as possible what has been done, and its success depends entirely on the synergy we bring to creating content. In fact, these resources are just the tip of the iceberg in terms of the relationships and links we can forge with each other on our work.

If you'd like to contribute in some way, the key is not to be discouraged by the size of the task, which can be frightening, but to start by taking the first step. You'll quickly realize that behind any problem or obstacle, you'll find a rich and friendly community that'll be able to help you, always with the aim of sharing and optimizing informatics resources.

Behind the many different types of content we can share with each other, from markdown documentation to packages or software developed by the community, the idea is to establish standards between us that guarantee the integrity and interoperability of the content and resources available. These standards can be seen as rules, but in no way should they be assimilated to barriers to your involvement. For example, if you're stuck on specific points (such as translating a procedure into another language or not knowing how to use forges such as git), turn to the community and you'll find all the help you need.

In general, here are a few guidelines to be considered before publishing resources:

* the resources on this site are intended to be used by all UMR, but also potentially by associated partners. By default, content must be published in French, but also in English to ensure maximum accessibility. Some content, such as training courses, may be exempted from these rules if this is relevant. Once again, don't let the language barrier stop you - you're guaranteed to find someone in our community who can help you translate.
* depending on the type of content you want to publish, it's sometimes best to turn to resource persons or referents who can provide you with solutions or proposals to guide you in sharing your resources. In the meantime, if you don't know who to turn to, you can send an e-mail to [DEN administrators](mailto:marbec-den-admin@listes.ird.fr).
* templates will be proposed for the different types of resources, with a view to sharing and overall harmony. In the meantime, don't hesitate to get in touch with other members of the community to try and find a common structure wherever possible.
* even if the use of informatics resources within the UMR is really to be seen in a transversal way and without associated “borders”, the mutualization and accessibility of the resources is really in connection with the Digital Ecology Device, or [DEN](https://umr-marbec.fr/recherche/dispositifs-de-recherche/den/){.external target=“_blank”}. This entity, which is transversal to the UMR, aims to set up, coordinate and pool technical resources, as well as exchange methodologies and new approaches in support of the digital aspects of scientific research. Getting closer to this organization and its sub-entities could be a wise move, and provide you with significant support for your activities.
* By its very essence, this site is designed to evolve as needs change. Don't hesitate to suggest improvements, new sections or even a different organization. In the end, this will only benefit the community.
:::